version: '3'
services:
  connector-misp:
    image: opencti/connector-misp:latest
    environment:
      - OPENCTI_URL=http://localhost:8080
      - OPENCTI_TOKEN=df8635b1-39b5-41c2-8873-2f19b0e6ca8c # 1
      - CONNECTOR_ID=7a9d21f1-9dbf-4ba5-bb81-99cf1b4cecf2 # 2
      - CONNECTOR_TYPE=EXTERNAL_IMPORT
      - CONNECTOR_NAME=MISP
      - CONNECTOR_SCOPE=misp
      - CONNECTOR_CONFIDENCE_LEVEL=3
      - CONNECTOR_UPDATE_EXISTING_DATA=false
      - CONNECTOR_LOG_LEVEL=info
      - MISP_URL=https://192.168.83.176/events/restSearch # Required3
      - MISP_KEY=tqd3z1gwmXuax3L8GOLJQgdPa8wPpsn7dMEtIfDL # Required4
      - MISP_SSL_VERIFY=False # Required
      - MISP_CREATE_REPORTS=True # Required, create report for MISP event
      - MISP_REPORT_CLASS=MISP\ event # Optional, report_class if creating report for event
      - MISP_IMPORT_FROM_DATE=2020-01-01 # Optional, import all event from this date
      - MISP_IMPORT_TAGS=opencti:import,type:osint # Optional, list of tags used for import events
      - MISP_INTERVAL=1 # Required, in minutes
    restart: always
